# Define the properties of the sensitive data under protection.
[data]
data_class_guid = "wedpr-table-test"
# data_class_name = "com.abc.bill"
# data_value_decimal = 2
# data_value_split_api = ["1->2", "2->1"]

    # Control how the sensitive data will be stored.
    [data.storage]
    adapter_type = "blockchain.fisco-bcos" # fabric
    adapter_version = "2.1"
    storage_controller_type = "smart-contract.solidity" # move
    storage_controller_version = "1.0"

[resource-generation]
# Control whether to generate the complete client code.
enable_client_code_generation = true

    # Control which langauge will be used in the generated code templates.
    [resource-generation.output]
    output_language = "java"

        # Control java specific settings.
        # [resource-generation.output.java]
        # java_package_prefix = "com.wedpr.sample"

[resource-anonymous_auction]
    [resource-anonymous_auction.workflow]
    enabled = false
    redeemable_everywhere = false
    # Add more parameters used by the data anonymous_auction template.

[resource-anonymous_voting]
    [resource-anonymous_voting.workflow]
    enabled = true
    redeemable_everywhere = false
    # Add more parameters used by the data hiding workflow template.

    [resource-anonymous_voting.workflow.unbounded]
    enabled = true
    # Add more parameters used by the auditing workflow template.

    [resource-anonymous_voting.workflow.bounded]
    enabled = true
    # Add more parameters used by the recovery workflow template.

[resource-hidden_asset]
    [resource-hidden_asset.workflow]
    enabled = true
    redeemable_everywhere = false
    # Add more parameters used by the data hiding workflow template.

    [resource-hidden_asset.workflow.data-auditing]
    enabled = true
    # Add more parameters used by the auditing workflow template.

    [resource-hidden_asset.workflow.data-recovery]
    enabled = false
    # Add more parameters used by the recovery workflow template.